import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // ── Navbar ──
    nav_home: 'Home',
    nav_about: 'About Studio',
    nav_contact: 'Contact',

    // ── Home / Hero ──
    hero_poetic_1: 'Create a memory with your baby',
    hero_poetic_2: 'Mission Verse transforms your precious moments into memories that last forever',

    // ── Home / V1 Frames ──
    frame1_title: 'Precious memories, in an environment designed for your baby',
    frame1_sub: 'At <strong>Mission Verse</strong>, every baby deserves a unique memory.',
    frame1_p1: 'In our studio, we create <strong>photo and video sessions specially dedicated to newborns</strong>, adapted to their age and needs.',
    frame1_p2: 'From <strong>10 days</strong>, we offer personalized sessions to immortalize the first moments of your baby through delicate photos, creative setups and unique videos.',
    frame2_sub: 'A VIP experience, designed for baby and mom',
    frame2_p1: 'The safety and comfort of your baby are our priority. Our sessions take place in a <strong>calm, clean and carefully prepared</strong> environment, with special attention to the newborn\'s comfort.',
    frame2_p2: 'We also want every mom to experience this <strong>serenely and comfortably</strong>, without stress or rush.',
    frame2_p3: 'Each session is organized according to the <strong>rhythm, age and needs of the baby</strong>, to create a gentle and personalized experience.',
    frame3_sub: 'Your baby. Their first memory. Our expertise.',
    frame3_p: 'From set preparation to the final creation of your photos and videos, <strong>Mission Verse transforms the first days of your baby into precious memories to keep for a lifetime.</strong>',
    frame3_btn: 'Book your Newborn session',

    // ── Home / Photo Marquee ──
    marquee_title: 'Our Most Beautiful Newborn Portraits',

    // ── About Page ──
    about_title: 'The Art of Capturing the Unforgettable',
    about_sub: 'At <strong>Mission Verse</strong>, we transform your baby\'s precious first moments into 4K cinematic works and timeless art portraits.',
    about_card1_title: '4K Cinema Videography',
    about_card1_p: 'Our films capture every breath, every little yawn and the pure emotions of your newborn with exceptional cinematic quality.',
    about_card2_title: 'Safety & Absolute Comfort',
    about_card2_p: 'Every session takes place in a 25°C heated environment, UV disinfected and adapted to your baby\'s natural rhythm, without any rush.',
    about_card3_title: 'Memories for Life',
    about_card3_p: 'From set preparation to custom color retouching, we create family treasures you will cherish forever.',

    // ── Contact Page ──
    contact_title: 'Contact',
    contact_tagline: 'Close-up on your memories and much more',
    contact_address_label: 'Address',
    contact_address_value: 'Mall Bouwaher, Biskra Road\nWilaya of Batna',
    contact_phone_label: 'Phone',
    contact_whatsapp_label: 'WhatsApp',
    contact_availability_label: 'Availability',
    contact_availability_value: 'We work by appointment',

    // ── Footer ──
    footer_subtitle: 'Development and communication company',
    footer_copyright: '© 2026 Mission Verse. All rights reserved.',
    footer_tel: 'Tel',

    // ── Mobile Bottom Bar ──
    mobile_call: 'Call Us',
    mobile_whatsapp: 'WhatsApp',
    mobile_reels: '4K Reels',
    mobile_book: 'Book Now',

    // ── FAQ ──
    faq_badge: 'Parent Questions & Answers',
    faq_title: 'Frequently Asked Questions',
    faq_sub: 'Everything you need to know before stepping into our warm, baby-safe cinema studio.',
    faq_q1: 'When is the ideal time to book and film a newborn shooting session?',
    faq_a1: 'The golden window for newborn photography and cinematic video is between 5 to 14 days after birth. During this sweet period, babies are very sleepy and naturally curl into peaceful womb-like poses. We recommend reserving your session during your second or third trimester based on your estimated due date; we will adjust the exact shoot date once baby arrives!',
    faq_q2: 'What safety precautions and sanitization standards are followed in the studio?',
    faq_a2: 'Baby safety is our highest pledge. Our studio space is heated to a comfortable 25°C (77°F) to ensure baby remains cozy and warm. All swaddles, organic blankets, and handcrafted wooden props are sanitized before every single session using hospital-grade UV sterilization and non-toxic pediatric detergents. Our videographers and photographers are certified newborn safety specialists.',
    faq_q3: 'Do parents and siblings participate in the shoot and video film?',
    faq_a3: 'Absolutely! We love filming and photographing the emotional bond between parents, older siblings, and the new baby. Sibling and family portraits are included in our Cinematic Milestone and Royal Heirloom collections with no extra hidden charge.',
    faq_q4: 'What do parents need to prepare or bring to the studio session?',
    faq_a4: 'You only need to bring baby essentials: extra milk or formula, diapers, wipes, and a soothing pacifier. We provide everything else — hundreds of couture swaddles, headbands, bonnets, handcrafted props, neutral parent gowns, and cozy lounge snacks in our private nursery suite.',
    faq_q5: 'When and how will we receive our 4K video reel and photo gallery?',
    faq_a5: 'You will receive your 4K teaser video reel within 48 to 72 hours so you can share the joyous arrival with loved ones immediately! Your complete collection of masterfully color-graded 4K films and retouched heirloom images will be ready in your private online gallery within 10 to 14 days.',

    // ── Packages ──
    pkg_badge: 'Curated Session Collections',
    pkg_title: 'Invest in Memories That Never Fade',
    pkg_sub: 'Transparent, luxury packages tailored for newborn and milestone sessions with cinema-grade video storytelling.',
    pkg_per_session: '/ session',
    pkg_select: 'Select Package',
    pkg_reserve: 'Reserve This Package',
    pkg_miracle_name: 'The Little Miracle',
    pkg_miracle_sub: 'Essential Fine-Art Photo & Reel',
    pkg_miracle_badge: 'Starter Choice',
    pkg_miracle_duration: '2 Hours Session',
    pkg_miracle_photos: '20 High-Res Edited Photos',
    pkg_miracle_video: '60-Sec 4K Social Video Reel',
    pkg_miracle_f1: 'Full access to sanitized baby wardrobe & props',
    pkg_miracle_f2: '20 High-resolution retouched digital images',
    pkg_miracle_f3: '60-second 4K cinematic Instagram/TikTok reel',
    pkg_miracle_f4: 'Gentle temperature-controlled studio environment',
    pkg_miracle_f5: 'Private online download gallery with printing rights',
    pkg_cinematic_name: 'Cinematic Milestone',
    pkg_cinematic_sub: 'Our Signature Photo & 4K Film Duo',
    pkg_cinematic_badge: '★ Most Popular & Loved',
    pkg_cinematic_duration: '3.5 Hours Relaxed Session',
    pkg_cinematic_photos: '40 High-Res Edited Photos',
    pkg_cinematic_video: '4K Cinematic Film (2-3 min) + 60s Reel',
    pkg_cinematic_f1: 'Signature 4K Master Cinema Film (with custom score)',
    pkg_cinematic_f2: '40 Masterfully color-graded heirloom portraits',
    pkg_cinematic_f3: 'Parents & sibling portraits included at no extra fee',
    pkg_cinematic_f4: '5 Curated baby setups (wooden props, clouds, nests)',
    pkg_cinematic_f5: 'Sneak peek 4K reel delivered within 48 hours',
    pkg_cinematic_f6: 'High-resolution print release + mobile app gallery',
    pkg_royal_name: 'The Royal Heirloom',
    pkg_royal_sub: 'Complete Archival Cinema & Keepsake',
    pkg_royal_badge: 'Ultimate Luxury',
    pkg_royal_duration: 'Unlimited Studio Time',
    pkg_royal_photos: '60+ Fine-Art Heirloom Photos',
    pkg_royal_video: 'Full 5-Min 4K Documentary + 2 Reels',
    pkg_royal_f1: '5-Minute 4K Mini-Documentary of your baby\'s story',
    pkg_royal_f2: 'Bespoke 10x10 Handcrafted Italian Linen Photo Album',
    pkg_royal_f3: 'All 60+ fully retouched archival quality images',
    pkg_royal_f4: 'Full family, siblings, and grandparents coverage',
    pkg_royal_f5: 'Expedited 48-hour delivery on all video deliverables',
    pkg_royal_f6: 'Custom engraved wooden USB keepsake box & print set',
    pkg_addons_title: 'Custom Session Add-Ons',
    pkg_addons_tip: 'Enhance your collection with luxury physical heirlooms and fast delivery',
    pkg_addon_album: 'Handcrafted Velvet Linen Photo Album (10x10)',
    pkg_addon_sibling: 'Grandparents & Sibling Milestone Film Segment',
    pkg_addon_rush: 'Expedited 48-Hour Delivery Guarantee',
    pkg_addon_raw: 'All Uncut Raw 4K Video Clips on SSD',
    pkg_selected_collection: 'Selected Collection:',
    pkg_addons_count: 'Add-on(s)',
    pkg_total: 'Total Estimated:',
    pkg_book_collection: 'Book This Collection',

    // ── Video Reel Player ──
    vid_badge: 'Cinematic Baby Videography',
    vid_title: 'Living Memories in 4K Cinema Motion',
    vid_sub: 'Photographs freeze a moment, but our signature 4K baby films capture the breath, the gentle sighs, and the unrepeatable first days of your baby\'s journey.',
    vid_rec_label: '4K CINEMA MASTER REEL',
    vid_book_style: 'Book This Video Style',
    vid_ambience_muted: 'Ambience Muted',
    vid_ambience_on: 'Lullaby Sound Master',
    vid_reel1_title: 'Newborn Slumber Symphony (4K Cinema)',
    vid_reel1_cat: 'Newborn Film (5-12 Days)',
    vid_reel1_desc: 'Slow-motion 60fps cinematic film capturing the peaceful dreams, tiny yawns, and rhythmic breathing of baby Liam on his 8th day of life.',
    vid_reel2_title: 'The Little Explorer - Sitter Milestone',
    vid_reel2_cat: 'Milestone Film (6-9 Months)',
    vid_reel2_desc: 'Joyful cinematic highlight capturing sparkling eyes, adorable belly laughs, and curious first grasps of wooden handcrafted toys.',
    vid_reel3_title: 'First Birthday Cake Smash Jubilee',
    vid_reel3_cat: '1st Birthday Film (12 Months)',
    vid_reel3_desc: 'An explosion of organic cream cake, giggles, pastel confetti, and happy little foot stomps captured in ultra-sharp 4K HDR.',
    vid_reel4_title: 'The Miracle of Touch - Family Story',
    vid_reel4_cat: 'Family & Newborn Cinema',
    vid_reel4_desc: 'Intimate emotional documentary film capturing the unrepeatable bond between parents and their newborn miracle in soft backlight.',
    vid_feat1_title: 'True 4K 60fps Cinema',
    vid_feat1_p: 'Shot with cinema-grade sensors capturing fine eyelash flutter and subtle smiles in ultra-high resolution.',
    vid_feat2_title: 'Custom Color Grading',
    vid_feat2_p: 'Every clip is hand-graded in our signature soft warm golden tones, ensuring skin tones look pristine and soft.',
    vid_feat3_title: 'Social Reel + Full Film',
    vid_feat3_p: 'Receive both an Instagram/TikTok ready 9:16 vertical teaser and a 16:9 full archival family documentary.',
    vid_feat4_title: 'Baby-Safe Lighting',
    vid_feat4_p: '100% continuous diffused warm softboxes with zero harsh strobes or sudden flashes for delicate baby eyes.',

    // ── Photo Gallery ──
    gal_badge: 'Masterpiece Portfolio',
    gal_title: 'Timeless Heirloom Baby Portraits',
    gal_sub: 'Every frame at Studio Mission Verse is an artistic celebration of new life, crafted with organic textures, soft continuous lighting, and safety-first posing.',
    gal_cat_all: 'All Curations',
    gal_cat_newborn: 'Newborn Dreams (5-14d)',
    gal_cat_milestone: 'Milestone Sitters (6-9m)',
    gal_cat_cakesmash: '1st Birthday Smash',
    gal_cat_family: 'Family & Newborn',
    gal_book_style: 'Book Style →',
    gal_lightbox_f1: 'Prop Sanitization: UV & Pediatric Organic Clean',
    gal_lightbox_f2: 'Includes 4K Video Reel & High-Res Retouched Images',
    gal_lightbox_f3: 'Continuous Eye-Safe Soft Lighting System',
    gal_lightbox_reserve: 'Reserve Session For This Style',
    gal_item1_title: 'Moonlit Slumber & Fairy Glow',
    gal_item1_age: 'Day 7 Newborn',
    gal_item1_theme: 'Rustic Crescent Moon & Angora Knit',
    gal_item1_desc: 'Gently swaddled in natural organic cashmere surrounded by ambient warm fairy lights.',
    gal_item2_title: 'The Little Explorer Sitter Session',
    gal_item2_age: '7 Months Sitter',
    gal_item2_theme: 'Natural Sheepskin & Wooden Keepsakes',
    gal_item2_desc: 'Capturing sparkling curious eyes, gentle giggles, and sitting milestones in neutral warm tones.',
    gal_item3_title: 'Boho First Birthday Smash',
    gal_item3_age: '12 Months Toddler',
    gal_item3_theme: 'Organic Buttercream & Gold Balloon Arch',
    gal_item3_desc: 'Joyful first taste of birthday cake surrounded by hand-tied pampas grass and gold accents.',
    gal_item4_title: 'The Purest Embrace',
    gal_item4_age: 'Day 10 Newborn + Parents',
    gal_item4_theme: 'Intimate Backlit Studio Portrait',
    gal_item4_desc: 'Timeless heirloom portrait capturing the warmth, devotion, and gentle kisses of mom and dad.',
    gal_item5_title: 'Sanitized Comfort Studio Suite',
    gal_item5_age: 'Behind the Scenes',
    gal_item5_theme: 'Temperature-Controlled Baby Suite (25°C)',
    gal_item5_desc: 'Our certified baby sanctuary featuring organic swaddle banks and nursing relaxation armchairs.',
    gal_item6_title: 'Angelic Whispers Macro Film',
    gal_item6_age: 'Day 9 Newborn',
    gal_item6_theme: 'Close-Up Eyelashes & Fleece Cocoon',
    gal_item6_desc: 'Fine-art macro capture revealing the exquisite fragility and serenity of baby Liam.',

    // ── Testimonials ──
    test_badge: 'Parent Love & Praise',
    test_title: 'Cherished by Over 800+ Happy Families',
    test_sub: 'Read why parents trust Studio Mission Verse to film and photograph their baby\'s once-in-a-lifetime beginnings.',
    test_t1_name: 'Elena & Marcus Vance',
    test_t1_baby: 'Baby Theo (Day 8 Newborn)',
    test_t1_story: 'When we received our 4K video reel, my husband and I both burst into tears of pure happiness. The way Studio Mission Verse captured our baby\'s sleepy yawns and tiny fingers with such soft cinematic light is simply unmatched. The studio was so warm, calm, and spotlessly clean.',
    test_t1_pkg: 'The Cinematic Milestone Collection',
    test_t1_tag: 'Verified Newborn Parent',
    test_t2_name: 'Sophia & David Chen',
    test_t2_baby: 'Baby Mia (1st Birthday Cake Smash)',
    test_t2_story: 'We were nervous Mia might cry during the cake smash, but the team had an angelic gentleness with her. The video recap looked like an authentic high-end movie! Our entire family in London and Tokyo watched the 4K link with pure awe. Worth every single penny.',
    test_t2_pkg: 'The Royal Heirloom Experience',
    test_t2_tag: '1st Birthday Milestone',
    test_t3_name: 'Amara & Julian Brooks',
    test_t3_baby: 'Baby Noah (7-Month Sitter)',
    test_t3_story: 'Safety was our number one concern as first-time parents. From the temperature-controlled nursery room to the UV sanitized props, Studio Mission Verse treated Noah like royalty. The photos and video reels are now our family\'s greatest treasure.',
    test_t3_pkg: 'The Cinematic Milestone Collection',
    test_t3_tag: 'Milestone Sitter Session',
  },

  fr: {
    // ── Navbar ──
    nav_home: 'Accueil',
    nav_about: 'À Propos',
    nav_contact: 'Contact',

    // ── Home / Hero ──
    hero_poetic_1: 'Créez un souvenir avec votre bébé',
    hero_poetic_2: 'Mission Verse transforme vos précieux moments en souvenirs qui restent pour toujours',

    // ── Home / V1 Frames ──
    frame1_title: 'Des souvenirs précieux, dans un environnement pensé pour votre bébé',
    frame1_sub: 'Chez <strong>Mission Verse</strong>, chaque bébé mérite un souvenir unique.',
    frame1_p1: 'Dans notre studio, nous créons des <strong>séances photo et vidéo spécialement dédiées aux nouveau-nés</strong>, adaptées à leur âge et à leurs besoins.',
    frame1_p2: 'À partir de <strong>10 jours</strong>, nous proposons des séances personnalisées pour immortaliser les premiers instants de votre bébé à travers des photos délicates, des mises en scène créatives et des vidéos uniques.',
    frame2_sub: 'Une expérience VIP, pensée pour bébé et maman',
    frame2_p1: 'La sécurité et le confort de votre bébé sont notre priorité. Nos séances sont réalisées dans un environnement <strong>calme, propre et soigneusement préparé</strong>, avec une attention particulière portée au confort du nouveau-né.',
    frame2_p2: 'Nous souhaitons également que chaque maman puisse vivre cette expérience <strong>sereinement et confortablement</strong>, sans stress ni précipitation.',
    frame2_p3: 'Chaque séance est donc organisée selon le <strong>rythme, l\'âge et les besoins du bébé</strong>, afin de créer une expérience douce et personnalisée.',
    frame3_sub: 'Votre bébé. Son premier souvenir. Notre savoir-faire.',
    frame3_p: 'De la préparation du décor jusqu\'à la création finale de vos photos et vidéos, <strong>Mission Verse transforme les premiers jours de votre bébé en souvenirs précieux à conserver pour toute une vie.</strong>',
    frame3_btn: 'Réservez votre séance Newborn',

    // ── Home / Photo Marquee ──
    marquee_title: 'Nos Plus Beaux Portraits de Nouveau-Nés',

    // ── About Page ──
    about_title: 'L\'Art de Capturer l\'Inoubliable',
    about_sub: 'Chez <strong>Mission Verse</strong>, nous transformons les premiers instants précieux de votre bébé en œuvres cinématographiques 4K et portraits d\'art intemporels.',
    about_card1_title: 'Vidéographie 4K Cinéma',
    about_card1_p: 'Nos films capturent chaque respiration, chaque petit bâillement et les émotions pures de votre nouveau-né avec une qualité cinématographique exceptionnelle.',
    about_card2_title: 'Sécurité & Confort Absolu',
    about_card2_p: 'Chaque séance est réalisée dans un environnement chauffé à 25°C, désinfecté par UV et adapté au rythme naturel de votre bébé, sans aucune précipitation.',
    about_card3_title: 'Souvenirs pour la Vie',
    about_card3_p: 'De la préparation des décors à la retouche couleur sur-mesure, nous créons des trésors familiaux que vous chérirez pour toujours.',

    // ── Contact Page ──
    contact_title: 'Contact',
    contact_tagline: 'Gros plan sur vos souvenirs et bien plus encore',
    contact_address_label: 'Adresse',
    contact_address_value: 'Mall Bouwaher, Route de Biskra\nWilaya de Batna',
    contact_phone_label: 'Téléphone',
    contact_whatsapp_label: 'WhatsApp',
    contact_availability_label: 'Disponibilité',
    contact_availability_value: 'Nous travaillons sur rendez-vous',

    // ── Footer ──
    footer_subtitle: 'Boîte de développement et communication',
    footer_copyright: '© 2026 Mission Verse. Tous droits réservés.',
    footer_tel: 'Tél',

    // ── Mobile Bottom Bar ──
    mobile_call: 'Appeler',
    mobile_whatsapp: 'WhatsApp',
    mobile_reels: 'Réels 4K',
    mobile_book: 'Réserver',

    // ── FAQ ──
    faq_badge: 'Questions & Réponses Parents',
    faq_title: 'Questions Fréquemment Posées',
    faq_sub: 'Tout ce que vous devez savoir avant de découvrir notre studio cinéma chaleureux et sûr pour bébé.',
    faq_q1: 'Quel est le moment idéal pour réserver une séance photo nouveau-né ?',
    faq_a1: 'La fenêtre idéale pour la photographie et la vidéo cinématographique nouveau-né se situe entre 5 et 14 jours après la naissance. Durant cette période, les bébés dorment beaucoup et adoptent naturellement des poses paisibles. Nous recommandons de réserver votre séance durant le deuxième ou troisième trimestre de grossesse ; nous ajusterons la date exacte une fois que bébé sera là !',
    faq_q2: 'Quelles précautions de sécurité et normes de désinfection sont respectées ?',
    faq_a2: 'La sécurité de bébé est notre engagement absolu. Notre studio est chauffé à 25°C pour garantir confort et chaleur. Tous les langes, couvertures biologiques et accessoires en bois sont désinfectés avant chaque séance avec une stérilisation UV de qualité hospitalière et des détergents pédiatriques non toxiques. Nos vidéastes et photographes sont des spécialistes certifiés en sécurité nouveau-né.',
    faq_q3: 'Les parents et frères et sœurs participent-ils à la séance ?',
    faq_a3: 'Absolument ! Nous adorons filmer et photographier le lien émotionnel entre les parents, les frères et sœurs aînés et le nouveau-né. Les portraits de famille sont inclus dans nos collections Cinematic Milestone et Royal Heirloom sans frais supplémentaires.',
    faq_q4: 'Que doivent préparer ou apporter les parents ?',
    faq_a4: 'Il vous suffit d\'apporter les essentiels de bébé : lait supplémentaire, couches, lingettes et tétine. Nous fournissons tout le reste — des centaines de langes couture, bandeaux, bonnets, accessoires faits main, tenues neutres pour parents et collations dans notre suite nurserie privée.',
    faq_q5: 'Quand et comment recevrons-nous notre vidéo 4K et galerie photo ?',
    faq_a5: 'Vous recevrez votre teaser vidéo 4K dans les 48 à 72 heures pour partager immédiatement la joyeuse nouvelle ! Votre collection complète de films 4K et d\'images retouchées sera prête dans votre galerie en ligne privée sous 10 à 14 jours.',

    // ── Packages ──
    pkg_badge: 'Collections de Séances Sélectionnées',
    pkg_title: 'Investissez dans des Souvenirs Éternels',
    pkg_sub: 'Des forfaits transparents et luxueux pour les séances nouveau-né et étapes clés avec vidéo cinématographique.',
    pkg_per_session: '/ séance',
    pkg_select: 'Choisir ce Forfait',
    pkg_reserve: 'Réserver ce Forfait',
    pkg_miracle_name: 'Le Petit Miracle',
    pkg_miracle_sub: 'Photo Fine-Art & Reel Essentiel',
    pkg_miracle_badge: 'Choix Découverte',
    pkg_miracle_duration: 'Séance de 2 Heures',
    pkg_miracle_photos: '20 Photos HD Retouchées',
    pkg_miracle_video: 'Reel Vidéo Social 4K de 60 Sec',
    pkg_miracle_f1: 'Accès complet à la garde-robe et accessoires désinfectés',
    pkg_miracle_f2: '20 Images numériques haute résolution retouchées',
    pkg_miracle_f3: 'Reel cinématique 4K de 60 secondes Instagram/TikTok',
    pkg_miracle_f4: 'Environnement studio à température contrôlée',
    pkg_miracle_f5: 'Galerie de téléchargement en ligne avec droits d\'impression',
    pkg_cinematic_name: 'Milestone Cinématique',
    pkg_cinematic_sub: 'Notre Duo Photo & Film 4K Signature',
    pkg_cinematic_badge: '★ Le Plus Populaire',
    pkg_cinematic_duration: 'Séance Détendue de 3h30',
    pkg_cinematic_photos: '40 Photos HD Retouchées',
    pkg_cinematic_video: 'Film 4K (2-3 min) + Reel 60s',
    pkg_cinematic_f1: 'Film Cinéma 4K Signature (avec musique sur mesure)',
    pkg_cinematic_f2: '40 Portraits patrimoniaux aux couleurs magistralement étalonnées',
    pkg_cinematic_f3: 'Portraits parents et frères/sœurs inclus sans frais',
    pkg_cinematic_f4: '5 Mises en scène bébé (accessoires bois, nuages, nids)',
    pkg_cinematic_f5: 'Aperçu reel 4K livré sous 48 heures',
    pkg_cinematic_f6: 'Droits d\'impression haute résolution + galerie mobile',
    pkg_royal_name: 'L\'Héritage Royal',
    pkg_royal_sub: 'Cinéma Archival Complet & Souvenirs',
    pkg_royal_badge: 'Luxe Ultime',
    pkg_royal_duration: 'Temps Studio Illimité',
    pkg_royal_photos: '60+ Photos Fine-Art Patrimoniales',
    pkg_royal_video: 'Documentaire 4K de 5 Min + 2 Reels',
    pkg_royal_f1: 'Mini-documentaire 4K de 5 minutes de l\'histoire de votre bébé',
    pkg_royal_f2: 'Album photo 10x10 artisanal en lin italien sur mesure',
    pkg_royal_f3: 'Plus de 60 images retouchées de qualité archivale',
    pkg_royal_f4: 'Couverture famille complète, frères/sœurs et grands-parents',
    pkg_royal_f5: 'Livraison accélérée 48h sur tous les livrables vidéo',
    pkg_royal_f6: 'Coffret USB en bois gravé personnalisé & jeu d\'impressions',
    pkg_addons_title: 'Suppléments de Séance Personnalisés',
    pkg_addons_tip: 'Enrichissez votre collection avec des souvenirs physiques de luxe et une livraison rapide',
    pkg_addon_album: 'Album Photo en Lin Velours Artisanal (10x10)',
    pkg_addon_sibling: 'Segment Film Grands-Parents & Frères/Sœurs',
    pkg_addon_rush: 'Garantie de Livraison Accélérée 48H',
    pkg_addon_raw: 'Tous les Clips 4K Bruts Non Coupés sur SSD',
    pkg_selected_collection: 'Collection Sélectionnée :',
    pkg_addons_count: 'Supplément(s)',
    pkg_total: 'Total Estimé :',
    pkg_book_collection: 'Réserver cette Collection',

    // ── Video Reel Player ──
    vid_badge: 'Vidéographie Cinématique Bébé',
    vid_title: 'Des Souvenirs Vivants en Cinéma 4K',
    vid_sub: 'Les photographies figent un instant, mais nos films 4K signature capturent le souffle, les soupirs doux et les premiers jours irrépétibles du parcours de votre bébé.',
    vid_rec_label: 'REEL MASTER CINÉMA 4K',
    vid_book_style: 'Réserver ce Style Vidéo',
    vid_ambience_muted: 'Ambiance Coupée',
    vid_ambience_on: 'Son Berceuse Master',
    vid_reel1_title: 'Symphonie du Sommeil Nouveau-Né (Cinéma 4K)',
    vid_reel1_cat: 'Film Nouveau-Né (5-12 Jours)',
    vid_reel1_desc: 'Film cinématique au ralenti 60fps capturant les rêves paisibles, les petits bâillements et la respiration rythmique du bébé Liam à son 8ème jour de vie.',
    vid_reel2_title: 'Le Petit Explorateur - Étape Assis',
    vid_reel2_cat: 'Film Étape (6-9 Mois)',
    vid_reel2_desc: 'Moment cinématique joyeux capturant des yeux pétillants, des rires adorables et les premières prises de jouets en bois artisanaux.',
    vid_reel3_title: 'Jubilé Gâteau Smash Premier Anniversaire',
    vid_reel3_cat: 'Film 1er Anniversaire (12 Mois)',
    vid_reel3_desc: 'Une explosion de gâteau crème bio, de rires, de confettis pastel et de petits pieds joyeux capturés en 4K HDR ultra-net.',
    vid_reel4_title: 'Le Miracle du Toucher - Histoire Familiale',
    vid_reel4_cat: 'Cinéma Famille & Nouveau-Né',
    vid_reel4_desc: 'Film documentaire intime et émouvant capturant le lien irremplaçable entre les parents et leur miracle nouveau-né en contre-jour doux.',
    vid_feat1_title: 'Vrai Cinéma 4K 60fps',
    vid_feat1_p: 'Filmé avec des capteurs cinéma capturant le frémissement des cils et les sourires subtils en ultra-haute résolution.',
    vid_feat2_title: 'Étalonnage Couleur Sur Mesure',
    vid_feat2_p: 'Chaque clip est étalonné à la main dans nos tons dorés chauds signature, pour des teints de peau impeccables.',
    vid_feat3_title: 'Reel Social + Film Complet',
    vid_feat3_p: 'Recevez un teaser vertical 9:16 pour Instagram/TikTok et un documentaire familial 16:9 archival.',
    vid_feat4_title: 'Éclairage Sûr pour Bébé',
    vid_feat4_p: '100% softboxes diffusées continues sans stroboscopes ou flashs soudains pour les yeux délicats.',

    // ── Photo Gallery ──
    gal_badge: 'Portfolio Chef-d\'Œuvre',
    gal_title: 'Portraits de Bébé Patrimoniaux Intemporels',
    gal_sub: 'Chaque image chez Studio Mission Verse est une célébration artistique de la nouvelle vie, réalisée avec des textures organiques, un éclairage continu doux et des poses sécuritaires.',
    gal_cat_all: 'Toutes les Créations',
    gal_cat_newborn: 'Rêves Nouveau-Né (5-14j)',
    gal_cat_milestone: 'Étapes Assis (6-9m)',
    gal_cat_cakesmash: 'Smash 1er Anniversaire',
    gal_cat_family: 'Famille & Nouveau-Né',
    gal_book_style: 'Réserver ce Style →',
    gal_lightbox_f1: 'Désinfection des Accessoires : UV & Nettoyage Bio Pédiatrique',
    gal_lightbox_f2: 'Inclut Reel Vidéo 4K & Images Retouchées Haute Résolution',
    gal_lightbox_f3: 'Système d\'Éclairage Doux Continu Sûr pour les Yeux',
    gal_lightbox_reserve: 'Réserver une Séance dans ce Style',
    gal_item1_title: 'Sommeil au Clair de Lune & Lumière Féerique',
    gal_item1_age: 'Nouveau-Né Jour 7',
    gal_item1_theme: 'Croissant de Lune Rustique & Tricot Angora',
    gal_item1_desc: 'Doucement emmailloté dans du cachemire bio naturel entouré de lumières féeriques chaleureuses.',
    gal_item2_title: 'Séance Petit Explorateur Assis',
    gal_item2_age: 'Assis 7 Mois',
    gal_item2_theme: 'Peau de Mouton Naturelle & Souvenirs en Bois',
    gal_item2_desc: 'Capturant des yeux curieux pétillants, des rires doux et les étapes assises dans des tons chauds neutres.',
    gal_item3_title: 'Smash Boho Premier Anniversaire',
    gal_item3_age: 'Bambin 12 Mois',
    gal_item3_theme: 'Crème au Beurre Bio & Arche de Ballons Dorés',
    gal_item3_desc: 'Première dégustation joyeuse du gâteau d\'anniversaire entouré d\'herbes de la pampa et d\'accents dorés.',
    gal_item4_title: 'L\'Étreinte la Plus Pure',
    gal_item4_age: 'Nouveau-Né Jour 10 + Parents',
    gal_item4_theme: 'Portrait Studio Intime en Contre-Jour',
    gal_item4_desc: 'Portrait patrimonial intemporel capturant la chaleur, la dévotion et les doux baisers de maman et papa.',
    gal_item5_title: 'Suite Studio Confort Désinfectée',
    gal_item5_age: 'Coulisses',
    gal_item5_theme: 'Suite Bébé à Température Contrôlée (25°C)',
    gal_item5_desc: 'Notre sanctuaire bébé certifié avec des rangements de langes bio et des fauteuils de relaxation allaitement.',
    gal_item6_title: 'Murmures Angéliques Film Macro',
    gal_item6_age: 'Nouveau-Né Jour 9',
    gal_item6_theme: 'Gros Plan Cils & Cocon Polaire',
    gal_item6_desc: 'Capture macro fine-art révélant la fragilité exquise et la sérénité du bébé Liam.',

    // ── Testimonials ──
    test_badge: 'Amour & Éloges des Parents',
    test_title: 'Chéri par Plus de 800+ Familles Heureuses',
    test_sub: 'Découvrez pourquoi les parents font confiance à Studio Mission Verse pour filmer et photographier les débuts uniques de leur bébé.',
    test_t1_name: 'Elena & Marcus Vance',
    test_t1_baby: 'Bébé Theo (Nouveau-Né Jour 8)',
    test_t1_story: 'Quand nous avons reçu notre reel vidéo 4K, mon mari et moi avons éclaté en larmes de pur bonheur. La façon dont Studio Mission Verse a capturé les bâillements endormis et les petits doigts de notre bébé avec une lumière cinématique si douce est tout simplement inégalée. Le studio était si chaud, calme et impeccablement propre.',
    test_t1_pkg: 'La Collection Cinematic Milestone',
    test_t1_tag: 'Parent Nouveau-Né Vérifié',
    test_t2_name: 'Sophia & David Chen',
    test_t2_baby: 'Bébé Mia (Smash Gâteau 1er Anniversaire)',
    test_t2_story: 'Nous étions inquiets que Mia pleure pendant le cake smash, mais l\'équipe avait une douceur angélique avec elle. Le récapitulatif vidéo ressemblait à un authentique film haut de gamme ! Toute notre famille à Londres et Tokyo a regardé le lien 4K avec pure admiration. Chaque centime en valait la peine.',
    test_t2_pkg: 'L\'Expérience Royal Heirloom',
    test_t2_tag: 'Étape 1er Anniversaire',
    test_t3_name: 'Amara & Julian Brooks',
    test_t3_baby: 'Bébé Noah (Assis 7 Mois)',
    test_t3_story: 'La sécurité était notre préoccupation numéro un en tant que nouveaux parents. De la chambre nurserie à température contrôlée aux accessoires désinfectés UV, Studio Mission Verse a traité Noah comme un roi. Les photos et les reels vidéo sont maintenant le plus grand trésor de notre famille.',
    test_t3_pkg: 'La Collection Cinematic Milestone',
    test_t3_tag: 'Séance Étape Assis',
  },

  ar: {
    // ── Navbar ──
    nav_home: 'الرئيسية',
    nav_about: 'عن الاستوديو',
    nav_contact: 'اتصل بنا',

    // ── Home / Hero ──
    hero_poetic_1: 'اصنعي ذكرى مع طفلك',
    hero_poetic_2: 'ميشن فيرس تحوّل لحظاتكم الثمينة إلى ذكريات تبقى للأبد',

    // ── Home / V1 Frames ──
    frame1_title: 'ذكريات ثمينة، في بيئة مصممة لراحة طفلك',
    frame1_sub: 'في <strong>ميشن فيرس</strong>، كل طفل يستحق ذكرى فريدة.',
    frame1_p1: 'في الاستوديو الخاص بنا، نقدم <strong>جلسات تصوير فوتوغرافي وفيديو مخصصة للمواليد الجدد</strong>، مكيّفة حسب عمرهم واحتياجاتهم.',
    frame1_p2: 'ابتداءً من <strong>10 أيام</strong>، نقدم جلسات مخصصة لتخليد اللحظات الأولى لطفلك من خلال صور رقيقة وديكورات إبداعية وفيديوهات فريدة.',
    frame2_sub: 'تجربة VIP، مصممة للطفل والأم',
    frame2_p1: 'سلامة وراحة طفلك هي أولويتنا. جلساتنا تتم في بيئة <strong>هادئة، نظيفة ومُعدّة بعناية</strong>، مع اهتمام خاص براحة المولود الجديد.',
    frame2_p2: 'نريد أيضًا أن تعيش كل أم هذه التجربة <strong>بهدوء وراحة</strong>، بدون ضغط أو استعجال.',
    frame2_p3: 'كل جلسة منظمة حسب <strong>إيقاع وعمر واحتياجات الطفل</strong>، لخلق تجربة لطيفة ومخصصة.',
    frame3_sub: 'طفلك. ذكراه الأولى. خبرتنا.',
    frame3_p: 'من إعداد الديكور إلى الإنتاج النهائي لصوركم وفيديوهاتكم، <strong>ميشن فيرس تحوّل الأيام الأولى لطفلك إلى ذكريات ثمينة تحتفظون بها مدى الحياة.</strong>',
    frame3_btn: 'احجزي جلسة المولود الجديد',

    // ── Home / Photo Marquee ──
    marquee_title: 'أجمل صور المواليد الجدد لدينا',

    // ── About Page ──
    about_title: 'فن التقاط اللحظات التي لا تُنسى',
    about_sub: 'في <strong>ميشن فيرس</strong>، نحوّل اللحظات الأولى الثمينة لطفلك إلى أعمال سينمائية 4K ولوحات فنية خالدة.',
    about_card1_title: 'تصوير فيديو سينمائي 4K',
    about_card1_p: 'أفلامنا تلتقط كل نفس، كل تثاؤب صغير والمشاعر النقية لمولودك الجديد بجودة سينمائية استثنائية.',
    about_card2_title: 'أمان وراحة مطلقة',
    about_card2_p: 'كل جلسة تتم في بيئة مدفأة إلى 25 درجة، معقمة بالأشعة فوق البنفسجية ومكيّفة حسب إيقاع طفلك الطبيعي، بدون أي استعجال.',
    about_card3_title: 'ذكريات مدى الحياة',
    about_card3_p: 'من إعداد الديكورات إلى تعديل الألوان المخصص، نصنع كنوزًا عائلية ستعتزون بها للأبد.',

    // ── Contact Page ──
    contact_title: 'اتصل بنا',
    contact_tagline: 'تكبير على ذكرياتكم وأكثر من ذلك بكثير',
    contact_address_label: 'العنوان',
    contact_address_value: 'مول بواهر، طريق بسكرة\nولاية باتنة',
    contact_phone_label: 'الهاتف',
    contact_whatsapp_label: 'واتساب',
    contact_availability_label: 'التوفر',
    contact_availability_value: 'نعمل بموعد مسبق',

    // ── Footer ──
    footer_subtitle: 'شركة تطوير وتواصل',
    footer_copyright: '© 2026 ميشن فيرس. جميع الحقوق محفوظة.',
    footer_tel: 'هاتف',

    // ── Mobile Bottom Bar ──
    mobile_call: 'اتصل بنا',
    mobile_whatsapp: 'واتساب',
    mobile_reels: 'ريلز 4K',
    mobile_book: 'احجز الآن',

    // ── FAQ ──
    faq_badge: 'أسئلة وأجوبة الآباء',
    faq_title: 'الأسئلة الشائعة',
    faq_sub: 'كل ما تحتاج معرفته قبل الدخول إلى استوديو السينما الدافئ والآمن للأطفال.',
    faq_q1: 'ما هو الوقت المثالي لحجز جلسة تصوير المولود الجديد؟',
    faq_a1: 'الفترة المثالية لتصوير المواليد الجدد هي بين 5 إلى 14 يومًا بعد الولادة. خلال هذه الفترة، ينام الأطفال كثيرًا ويتخذون وضعيات هادئة طبيعيًا. ننصح بحجز جلستك خلال الثلث الثاني أو الثالث من الحمل؛ وسنعدّل التاريخ الدقيق بعد وصول الطفل!',
    faq_q2: 'ما هي احتياطات السلامة ومعايير التعقيم المتبعة في الاستوديو؟',
    faq_a2: 'سلامة الطفل هي أعلى التزاماتنا. الاستوديو مدفأ إلى 25 درجة مئوية لضمان راحة ودفء الطفل. جميع اللفافات والبطانيات العضوية والإكسسوارات الخشبية معقمة قبل كل جلسة باستخدام تعقيم UV بمستوى المستشفيات ومنظفات أطفال غير سامة. المصورون لدينا متخصصون معتمدون في سلامة المواليد.',
    faq_q3: 'هل يشارك الآباء والإخوة في الجلسة والفيلم؟',
    faq_a3: 'بالتأكيد! نحب تصوير الرابطة العاطفية بين الآباء والإخوة الأكبر والمولود الجديد. صور العائلة مضمنة في مجموعاتنا Cinematic Milestone و Royal Heirloom بدون رسوم إضافية.',
    faq_q4: 'ما الذي يحتاج الآباء لتحضيره أو إحضاره؟',
    faq_a4: 'تحتاجون فقط لإحضار أساسيات الطفل: حليب إضافي، حفاضات، مناديل مبللة ولهاية. نوفر كل شيء آخر — مئات اللفافات، عصابات الرأس، القبعات، الإكسسوارات اليدوية، أزياء الآباء والوجبات الخفيفة في جناح الحضانة الخاص.',
    faq_q5: 'متى وكيف سنستلم فيديو 4K ومعرض الصور؟',
    faq_a5: 'ستستلمون فيديو 4K التشويقي خلال 48 إلى 72 ساعة لمشاركة الخبر السعيد فوراً! مجموعتكم الكاملة من أفلام 4K والصور المعدّلة ستكون جاهزة في معرضكم الخاص عبر الإنترنت خلال 10 إلى 14 يومًا.',

    // ── Packages ──
    pkg_badge: 'مجموعات جلسات منتقاة',
    pkg_title: 'استثمروا في ذكريات لا تتلاشى',
    pkg_sub: 'باقات شفافة وفاخرة مصممة لجلسات المواليد والمراحل المهمة مع فيديو سينمائي.',
    pkg_per_session: '/ جلسة',
    pkg_select: 'اختيار الباقة',
    pkg_reserve: 'حجز هذه الباقة',
    pkg_miracle_name: 'المعجزة الصغيرة',
    pkg_miracle_sub: 'صور فنية وريل أساسي',
    pkg_miracle_badge: 'الخيار الأول',
    pkg_miracle_duration: 'جلسة ساعتين',
    pkg_miracle_photos: '20 صورة عالية الدقة معدّلة',
    pkg_miracle_video: 'ريل فيديو اجتماعي 4K لمدة 60 ثانية',
    pkg_miracle_f1: 'وصول كامل للملابس والإكسسوارات المعقمة',
    pkg_miracle_f2: '20 صورة رقمية عالية الدقة معدّلة',
    pkg_miracle_f3: 'ريل سينمائي 4K لمدة 60 ثانية لانستغرام/تيك توك',
    pkg_miracle_f4: 'بيئة استوديو بدرجة حرارة مضبوطة',
    pkg_miracle_f5: 'معرض تحميل خاص عبر الإنترنت مع حقوق الطباعة',
    pkg_cinematic_name: 'الحدث السينمائي',
    pkg_cinematic_sub: 'ثنائي الصور والأفلام 4K المميز',
    pkg_cinematic_badge: '★ الأكثر شعبية',
    pkg_cinematic_duration: 'جلسة مريحة 3.5 ساعات',
    pkg_cinematic_photos: '40 صورة عالية الدقة معدّلة',
    pkg_cinematic_video: 'فيلم سينمائي 4K (2-3 دقائق) + ريل 60 ثانية',
    pkg_cinematic_f1: 'فيلم سينما 4K مميز (مع موسيقى مخصصة)',
    pkg_cinematic_f2: '40 صورة تراثية بألوان متقنة',
    pkg_cinematic_f3: 'صور الآباء والإخوة مضمنة بدون رسوم إضافية',
    pkg_cinematic_f4: '5 ديكورات أطفال (إكسسوارات خشبية، غيوم، أعشاش)',
    pkg_cinematic_f5: 'ريل معاينة 4K يُسلّم خلال 48 ساعة',
    pkg_cinematic_f6: 'حقوق طباعة عالية الدقة + معرض تطبيق الجوال',
    pkg_royal_name: 'الإرث الملكي',
    pkg_royal_sub: 'سينما أرشيفية كاملة وتذكارات',
    pkg_royal_badge: 'الفخامة المطلقة',
    pkg_royal_duration: 'وقت استوديو غير محدود',
    pkg_royal_photos: '60+ صورة فنية تراثية',
    pkg_royal_video: 'وثائقي 4K كامل 5 دقائق + ريلان',
    pkg_royal_f1: 'فيلم وثائقي مصغر 4K لمدة 5 دقائق لقصة طفلك',
    pkg_royal_f2: 'ألبوم صور 10x10 يدوي الصنع من الكتان الإيطالي',
    pkg_royal_f3: 'أكثر من 60 صورة معدّلة بجودة أرشيفية',
    pkg_royal_f4: 'تغطية العائلة الكاملة والإخوة والأجداد',
    pkg_royal_f5: 'تسليم سريع 48 ساعة لجميع مخرجات الفيديو',
    pkg_royal_f6: 'صندوق USB خشبي محفور مخصص ومجموعة طبعات',
    pkg_addons_title: 'إضافات الجلسة المخصصة',
    pkg_addons_tip: 'عززوا مجموعتكم بتذكارات فاخرة وتسليم سريع',
    pkg_addon_album: 'ألبوم صور من الكتان المخملي اليدوي (10x10)',
    pkg_addon_sibling: 'مقطع فيلم الأجداد والإخوة',
    pkg_addon_rush: 'ضمان التسليم السريع 48 ساعة',
    pkg_addon_raw: 'جميع المقاطع الخام 4K غير المقطوعة على SSD',
    pkg_selected_collection: 'المجموعة المختارة:',
    pkg_addons_count: 'إضافة/إضافات',
    pkg_total: 'الإجمالي المقدر:',
    pkg_book_collection: 'حجز هذه المجموعة',

    // ── Video Reel Player ──
    vid_badge: 'تصوير فيديو سينمائي للأطفال',
    vid_title: 'ذكريات حية بسينما 4K',
    vid_sub: 'الصور تجمّد لحظة، لكن أفلامنا 4K المميزة تلتقط النفَس والتنهدات اللطيفة والأيام الأولى التي لا تتكرر من رحلة طفلك.',
    vid_rec_label: 'ريل ماستر سينما 4K',
    vid_book_style: 'احجز هذا النمط',
    vid_ambience_muted: 'الصوت مكتوم',
    vid_ambience_on: 'صوت التهويدة الرئيسي',
    vid_reel1_title: 'سيمفونية نوم المولود الجديد (سينما 4K)',
    vid_reel1_cat: 'فيلم مولود جديد (5-12 يوم)',
    vid_reel1_desc: 'فيلم سينمائي بالحركة البطيئة 60fps يلتقط الأحلام الهادئة والتثاؤب الصغير والتنفس الإيقاعي للطفل ليام في يومه الثامن.',
    vid_reel2_title: 'المستكشف الصغير - مرحلة الجلوس',
    vid_reel2_cat: 'فيلم المراحل (6-9 أشهر)',
    vid_reel2_desc: 'لحظة سينمائية مبهجة تلتقط عيونًا متلألئة وضحكات محبوبة وأول إمساك بالألعاب الخشبية اليدوية.',
    vid_reel3_title: 'احتفال تحطيم الكيك - العيد الأول',
    vid_reel3_cat: 'فيلم العيد الأول (12 شهر)',
    vid_reel3_desc: 'انفجار من كيك الكريمة العضوية والضحكات وقصاصات الباستيل ودوس الأقدام الصغيرة السعيدة ملتقطة بـ 4K HDR فائق الوضوح.',
    vid_reel4_title: 'معجزة اللمسة - قصة عائلية',
    vid_reel4_cat: 'سينما العائلة والمولود الجديد',
    vid_reel4_desc: 'فيلم وثائقي حميم وعاطفي يلتقط الرابطة التي لا تتكرر بين الآباء ومعجزتهم حديثة الولادة في إضاءة خلفية ناعمة.',
    vid_feat1_title: 'سينما 4K حقيقية 60fps',
    vid_feat1_p: 'مصور بأجهزة استشعار سينمائية تلتقط رفرفة الرموش والابتسامات الخفية بدقة فائقة.',
    vid_feat2_title: 'تدرج لوني مخصص',
    vid_feat2_p: 'كل مقطع يُعدّل يدويًا بألواننا الذهبية الدافئة المميزة لضمان ألوان بشرة نقية وناعمة.',
    vid_feat3_title: 'ريل اجتماعي + فيلم كامل',
    vid_feat3_p: 'استلموا تيزر عمودي 9:16 لانستغرام/تيك توك ووثائقي عائلي 16:9 أرشيفي كامل.',
    vid_feat4_title: 'إضاءة آمنة للأطفال',
    vid_feat4_p: '100% إضاءة ناعمة مستمرة بدون فلاشات مفاجئة لعيون الأطفال الحساسة.',

    // ── Photo Gallery ──
    gal_badge: 'معرض الروائع',
    gal_title: 'صور أطفال تراثية خالدة',
    gal_sub: 'كل إطار في استوديو ميشن فيرس هو احتفال فني بالحياة الجديدة، مصنوع بأنسجة طبيعية وإضاءة ناعمة مستمرة ووضعيات آمنة.',
    gal_cat_all: 'جميع الإبداعات',
    gal_cat_newborn: 'أحلام المواليد (5-14 يوم)',
    gal_cat_milestone: 'مرحلة الجلوس (6-9 أشهر)',
    gal_cat_cakesmash: 'سماش العيد الأول',
    gal_cat_family: 'العائلة والمولود',
    gal_book_style: 'احجز هذا النمط ←',
    gal_lightbox_f1: 'تعقيم الإكسسوارات: UV ونظافة عضوية للأطفال',
    gal_lightbox_f2: 'يشمل ريل فيديو 4K وصور معدّلة عالية الدقة',
    gal_lightbox_f3: 'نظام إضاءة ناعمة مستمرة آمنة للعيون',
    gal_lightbox_reserve: 'احجز جلسة بهذا النمط',
    gal_item1_title: 'سبات ضوء القمر والتوهج الخيالي',
    gal_item1_age: 'مولود جديد يوم 7',
    gal_item1_theme: 'هلال ريفي وتريكو أنجورا',
    gal_item1_desc: 'ملفوف بلطف في كشمير عضوي طبيعي محاط بأضواء خيالية دافئة.',
    gal_item2_title: 'جلسة المستكشف الصغير الجالس',
    gal_item2_age: 'جالس 7 أشهر',
    gal_item2_theme: 'جلد خروف طبيعي وتذكارات خشبية',
    gal_item2_desc: 'التقاط عيون فضولية متلألئة وضحكات لطيفة ومراحل الجلوس بألوان دافئة محايدة.',
    gal_item3_title: 'سماش بوهو العيد الأول',
    gal_item3_age: 'طفل 12 شهر',
    gal_item3_theme: 'كريمة زبدة عضوية وقوس بالونات ذهبي',
    gal_item3_desc: 'أول تذوق فرح لكيك العيد محاط بعشب البامباس وزخارف ذهبية.',
    gal_item4_title: 'العناق الأنقى',
    gal_item4_age: 'مولود جديد يوم 10 + الآباء',
    gal_item4_theme: 'صورة استوديو حميمة بإضاءة خلفية',
    gal_item4_desc: 'صورة تراثية خالدة تلتقط الدفء والإخلاص والقبلات اللطيفة من الأم والأب.',
    gal_item5_title: 'جناح استوديو معقم ومريح',
    gal_item5_age: 'وراء الكواليس',
    gal_item5_theme: 'جناح أطفال بدرجة حرارة مضبوطة (25°)',
    gal_item5_desc: 'ملاذنا المعتمد للأطفال مع خزانات لفافات عضوية وكراسي استرخاء للرضاعة.',
    gal_item6_title: 'همسات ملائكية فيلم ماكرو',
    gal_item6_age: 'مولود جديد يوم 9',
    gal_item6_theme: 'تقريب رموش وشرنقة صوف',
    gal_item6_desc: 'تصوير ماكرو فني يكشف الهشاشة الرائعة وسكينة الطفل ليام.',

    // ── Testimonials ──
    test_badge: 'حب وثناء الآباء',
    test_title: 'محبوب من أكثر من 800+ عائلة سعيدة',
    test_sub: 'اكتشفوا لماذا يثق الآباء في استوديو ميشن فيرس لتصوير بدايات أطفالهم التي لا تتكرر.',
    test_t1_name: 'إيلينا وماركوس فانس',
    test_t1_baby: 'الطفل ثيو (مولود جديد يوم 8)',
    test_t1_story: 'عندما استلمنا ريل الفيديو 4K، انفجرت أنا وزوجي بالبكاء من شدة السعادة. الطريقة التي التقط بها استوديو ميشن فيرس تثاؤب طفلنا النائم وأصابعه الصغيرة بإضاءة سينمائية ناعمة لا مثيل لها. كان الاستوديو دافئًا وهادئًا ونظيفًا بشكل مثالي.',
    test_t1_pkg: 'مجموعة Cinematic Milestone',
    test_t1_tag: 'والد مولود جديد موثق',
    test_t2_name: 'صوفيا وديفيد تشن',
    test_t2_baby: 'الطفلة ميا (سماش كيك العيد الأول)',
    test_t2_story: 'كنا قلقين من أن ميا قد تبكي خلال تحطيم الكيك، لكن الفريق كان لديه رقة ملائكية معها. ملخص الفيديو بدا كفيلم راقي أصيل! عائلتنا بأكملها في لندن وطوكيو شاهدت رابط 4K بإعجاب كبير. كل قرش كان يستحق.',
    test_t2_pkg: 'تجربة Royal Heirloom',
    test_t2_tag: 'مرحلة العيد الأول',
    test_t3_name: 'أمارا وجوليان بروكس',
    test_t3_baby: 'الطفل نوح (جالس 7 أشهر)',
    test_t3_story: 'السلامة كانت قلقنا الأول كآباء لأول مرة. من غرفة الحضانة المدفأة إلى الإكسسوارات المعقمة بالأشعة فوق البنفسجية، عامل استوديو ميشن فيرس نوح كملك. الصور وريلات الفيديو هي الآن أعظم كنز لعائلتنا.',
    test_t3_pkg: 'مجموعة Cinematic Milestone',
    test_t3_tag: 'جلسة مرحلة الجلوس',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('fr');

  useEffect(() => {
    // Always keep LTR — no RTL even for Arabic per user request
    document.documentElement.setAttribute('dir', 'ltr');
    document.documentElement.setAttribute('lang', lang);
  }, [lang]);

  const t = (key) => translations[lang]?.[key] ?? translations['en']?.[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, language: lang, setLanguage: setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export default LanguageContext;
